Train/urls.py
from django.urls import path
from .import views



urlpatterns = [

    path('details/<int:id>/', views.DetailPostView.as_view(), name='detail_post'),
    path('cars/<int:book_id>/buy/', views.borrow_book, name='borrow_book'),
    # path('widthdraw/', WithdrawMoneyView.as_view, name='buy_car'),
]

library_management_system/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home,name='home'),
    path('users/',include('users.urls')),
    path('Train/',include('Train.urls')),
    path('category/<slug:category_slug>/', views.home, name='category_wise_post'),
    path('transactions/', include('transactions.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView,user_logout,profile,Passchange,UserBankAccountUpdateView,booking_seat,book_detail

 
urlpatterns = [
   path('register/', UserRegistrationView.as_view(), name='register'),
   path('login/', UserLoginView.as_view(), name='login'),
   path('Logout/', user_logout, name='logout'),
  #  path('profile/', profile, name='profile'),
   path('profile/', profile, name='profile'),
   path('profile/edit',UserBankAccountUpdateView.as_view(), name='edit_profile'),
  #  path('profile/edit',edit_profile, name='edit_profile'),
   path('Passchange/', Passchange,name='Passchange'),
   path('booking_seat/', booking_seat,name='booking_seat'),
   path('book_detail/<int:book_id>/',book_detail, name='book_detail' ),
   

 ]

Train/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone




class Station(models.Model):
    name = models.CharField(max_length=100)
    slug=models.SlugField(max_length=100,unique=True,null=True,blank=True)
    def __str__(self) :
        return f"{self.name}"

class Train(models.Model):
    name = models.CharField(max_length=100)
    schedule = models.TextField()
    image = models.ImageField(upload_to='Train/media/uploads/', blank = True, null = True)
    station=models.ManyToManyField(Station)
    quantity = models.IntegerField(default=0)
    borrowing_price = models.DecimalField(max_digits=10, decimal_places=2,default=0)

    
    def __str__(self):
        return str(self.name)
    


from django.utils import timezone

class BorrowingHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    train = models.ForeignKey(Train, on_delete=models.CASCADE)
    borrowing_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.user.username} borrowed {self.train.title} on {self.borrowing_date}"


class Comment(models.Model):
    train= models.ForeignKey(Train, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=30)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True) # jkhn e ei class er object toiri hobe sei time ta rekhe dibe
    
    def __str__(self):
        return f"Comments by {self.name}"
    
class seat(models.Model):
    train=models.ForeignKey(Train, on_delete=models.CASCADE)
    

users/models.py
from django.db import models
from django.contrib.auth.models import User
from .constants import ACCOUNT_TYPE, GENDER_TYPE
# django amaderke built in user niye kaj korar facility dey


class UserBankAccount(models.Model):
    user = models.OneToOneField(User, related_name='account', on_delete=models.CASCADE)
    account_type = models.CharField(max_length=10, choices=ACCOUNT_TYPE)
    account_no = models.IntegerField(unique=True) # account no duijon user er kokhono same hobe na
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_TYPE)
    initial_deposite_date = models.DateField(auto_now_add=True)
    
    balance = models.DecimalField(default=0, max_digits=12, decimal_places=2) # ekjon user 12 digit obdi taka rakhte parbe, dui doshomik ghor obdi rakhte parben 1000.50
    def __str__(self):
        return str(self.account_no)



class UserAddress(models.Model):
    user = models.OneToOneField(User, related_name='address', on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    city = models.CharField(max_length= 100)
    postal_code = models.IntegerField()
    country = models.CharField(max_length=100)
    nid = models.CharField(max_length=100 ,default='')
    def __str__(self):
        return str(self.user.email)

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .constants import ACCOUNT_TYPE, GENDER_TYPE
from django.contrib.auth.models import User
from .models import UserBankAccount, UserAddress

class UserRegistrationForm(UserCreationForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    gender = forms.ChoiceField(choices=GENDER_TYPE)
    account_type = forms.ChoiceField(choices=ACCOUNT_TYPE)
    street_address = forms.CharField(max_length=100)
    city = forms.CharField(max_length= 100)
    postal_code = forms.IntegerField()
    country = forms.CharField(max_length=100)
    nid = forms.CharField(max_length=100)
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'account_type', 'birth_date','gender', 'postal_code', 'city','country', 'street_address','nid']
        
    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields:
                self.fields[field].widget.attrs.update({
                    'class': (
                        'appearance-none block w-full bg-gray-200 '
                        'text-gray-700 border border-gray-200 rounded '
                        'py-3 px-4 leading-tight focus:outline-none '
                        'focus:bg-white focus:border-gray-500'
                    )
                })

        # form.save()
    def save(self, commit=True):
        our_user = super().save(commit=False) # ami database e data save korbo na ekhn
        if commit == True:
            our_user.save() # user model e data save korlam
            account_type = self.cleaned_data.get('account_type')
            gender = self.cleaned_data.get('gender')
            postal_code = self.cleaned_data.get('postal_code')
            country = self.cleaned_data.get('country')
            birth_date = self.cleaned_data.get('birth_date')
            city = self.cleaned_data.get('city')
            street_address = self.cleaned_data.get('street_address')
            nid = self.cleaned_data.get('nid')
            
            UserAddress.objects.create(
                user = our_user,
                postal_code = postal_code,
                country = country,
                city = city,
                street_address = street_address,
                nid=nid
            )
            UserBankAccount.objects.create(
                user = our_user,
                account_type  = account_type,
                gender = gender,
                birth_date =birth_date,
                account_no = 100000+ our_user.id
            )
        return our_user
    

from django import forms
from django.contrib.auth.models import User
from .models import UserBankAccount, UserAddress

GENDER_TYPE = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other'),
)

ACCOUNT_TYPE = (
    ('S', 'Savings'),
    ('C', 'Current'),
)

class UserUpdateForm(forms.ModelForm):
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    gender = forms.ChoiceField(choices=GENDER_TYPE)
    account_type = forms.ChoiceField(choices=ACCOUNT_TYPE)
    street_address = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    postal_code = forms.IntegerField()
    country = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'birth_date', 'gender', 'account_type', 'street_address', 'city', 'postal_code', 'country']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })
        if self.instance:
            try:
                user_account = self.instance.account
                user_address = self.instance.address
            except UserBankAccount.DoesNotExist:
                user_account = None
                user_address = None

            if user_account:
                self.fields['account_type'].initial = user_account.account_type
                self.fields['gender'].initial = user_account.gender
                self.fields['birth_date'].initial = user_account.birth_date
                self.fields['street_address'].initial = user_address.street_address
                self.fields['city'].initial = user_address.city
                self.fields['postal_code'].initial = user_address.postal_code
                self.fields['country'].initial = user_address.country

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            user_account, _ = UserBankAccount.objects.get_or_create(user=user)
            user_address, _ = UserAddress.objects.get_or_create(user=user)

            user_account.account_type = self.cleaned_data['account_type']
            user_account.gender = self.cleaned_data['gender']
            user_account.birth_date = self.cleaned_data['birth_date']
            user_account.save()

            user_address.street_address = self.cleaned_data['street_address']
            user_address.city = self.cleaned_data['city']
            user_address.postal_code = self.cleaned_data['postal_code']
            user_address.country = self.cleaned_data['country']
            user_address.save()

        return user

users/views.py
from django.shortcuts import render
from django.views.generic import FormView
from .forms import UserRegistrationForm,UserUpdateForm
from django.contrib.auth import login, logout,update_session_auth_hash
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.decorators import login_required
from django.views import View
from django.shortcuts import redirect
from django.contrib.auth.forms import PasswordChangeForm
from .forms import UserRegistrationForm
# ,ChangeUserForm
# ,UserUpdateForm


from django.contrib import messages

class UserRegistrationView(FormView):
    template_name = 'user_registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('register')
    
    def form_valid(self,form):
        print(form.cleaned_data)
        user = form.save()

        login(self.request, user)
        # print(user)
        return super().form_valid(form) # form_valid function call hobe jodi sob thik thake
    

class UserLoginView(LoginView):
    template_name = 'user_login.html'
    def get_success_url(self):
        return reverse_lazy('home')

# class UserLogoutView(LogoutView):
#     def get_success_url(self):
#         if self.request.user.is_authenticated:
#             logout(self.request)
#         return reverse_lazy('home')
def user_logout(request):
    logout(request)
    return redirect('home')

class UserBankAccountUpdateView(View):
    template_name = 'update_profile.html'

    def get(self, request):
        form = UserUpdateForm(instance=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')  # Redirect to the user's profile page
        return render(request, self.template_name, {'form': form})

# def profile(request):
#     return render(request,'profile.html')

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserUpdateForm  # Assuming you have a form for updating user profile

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import UserUpdateForm  # Assuming you have a form for updating user profile

@login_required
def profile(request):
    user = request.user  # Get the current user
    
    if request.method == 'POST':
        profile_form = UserUpdateForm(request.POST, instance=user)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile')  # Redirect to the profile page after successful update
    else:
        profile_form = UserUpdateForm(instance=user)  # Populate the form with current user data
    
    return render(request, 'profile.html', {'form': profile_form, 'user': user})


def Passchange(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(user=request.user, data=request.POST)
            if form.is_valid():
                form.save()
                # password update korbe
                update_session_auth_hash(request, form.user)
                return redirect('profile')
        else:
            form = PasswordChangeForm(user=request.user)
        return render(request, './passchange.html', {'form': form})
    else:
        return redirect('login')
    

def booking_seat(request):
    return render(request,'booking_seat.html')


from Train.models import Train, Comment
from Train.forms import CommentForm

def book_detail(request, book_id):
    train = Train.objects.get(pk=book_id)
    reviews = train.comments.all()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.train = train
            review.save()
            print(form.cleaned_data)
            return render(request, 'book_detail.html', {'book': train, 'reviews': reviews, 'form': form})
    else:
        form = CommentForm()
    return render(request, 'book_detail.html', {'book': train, 'reviews': reviews, 'form': form})

users/templates/book_detail.html
{% extends "base.html" %}
{% block content%}


<h1><strong>Name:</strong>{{ form.name }}</h2>
<strong>Review:</strong>{{ form.body }}</h2>

{% load crispy_forms_tags %}
<form method="post" style="width: 50%; height: 500px; margin:auto;" class="pt-4" 
enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary mt-2">Submit</button>



    
               
{% endblock %}

users/templates/booking_seat.html
{% extends "base.html" %}

{% block content %}


<table class="table table-bordered">
    <thead>
        <tr>
            
            <th scope="col">Train Name </th>
            <th scope="col">Seat Price</th>
            <th scope="col">Seat Selection Date</th>
            <th scope="col"> Review</th>
        </tr>
    </thead>
    <tbody>
        {% for order in user.borrowinghistory_set.all %}
        <tr>
           
            {% comment %} <td>{{ order.book.title }}</td> {% endcomment %}
            <td>
                {{ order.train.name }}
                
            </td>
            
            <td>{{ order.train.borrowing_price }}</td>
            <td>{{ order.borrowing_date }}</td>
            <td>
                <a class="nav-link btn btn-warning" href="{% url 'book_detail' order.train.id  %}">Click Me</a>
              </td>
            
        </tr>
        
        {% endfor %}
    </tbody>
</table>




 


<div>
    {% comment %} {% for post in form %} {% endcomment %}
    <h1>{{form.body}}</h1>
    {% comment %} {% endfor %} {% endcomment %}
</div>
{% endblock %}

users/templates/passchange.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
     <form method="post" style="width: 50%; margin: auto" novalidate>
       <h1>Password Change</h1>
       {% csrf_token %}
       {% if form.non_field_errors %}
       {% for er in form.non_field_errors %}
         <p class="bg-danger text-white p-3">{{er}}</p>
       {% endfor %}
       {% endif %}
       <!-- {{form | crispy }} -->
       {% for fm in form%} {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} 
       {% endfor %}
       <br />
       <button class="btn btn-primary" type="submit">Submit</button>
       <br/>
     </form>
     {% endblock %}

users/templates/profile.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}



  <div>
  <a class="btn btn-primary m-3" href="{% url 'edit_profile' %}">Edit Your Profile</a>
  <a class="btn btn-primary m-3" href="{% url 'Passchange' %}">Change Your Password</a>
</div>  

  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-6">
        <div class="card text-bg-success mb-3">
          <div class="card-header "><strong >Passenger Profile</strong> </div>
          <div class="card-body">
            <h1>First Name : {{ user.first_name  }}</h1>
            <h2 class="card-title">Last Name : {{ user.last_name }}</h2>
            <h2 class="card-title"> Email : {{ user.email }}</h2>
            <h2 class="card-title"> Email : {{ user.account.gender }}</h2>
            <h2 class="card-title">Street Adress : {{ user.address.street_address }}</h2>
            <h2 class="card-title">City: {{ user.address.country }}</h2>
            <h2 class="card-title">Country : {{ user.address.country }}</h2>
          </div>
        </div>


          </div>
        </div>
      </div>
    </div>
  </div>




{% endblock %} 

users/templates/update_profile.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Banking System{% endblock %}
{% block content %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
                <p class="font-bold">Error!</p>
                <p class="block sm:inline">{{ error }}</p>
            </div>
        {% endfor %}
    {% endif %}

    <div class="bg-white px-3 py-4 rounded-xl my-6">
        <h1 class="font-bold text-3xl text-center pb-5">Update Profile Information</h1>
        <div class="w-full mt-10">
            <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                {% csrf_token %}
                {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field.errors }}
                    {{ hidden_field }}
                {% endfor %}
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.first_name.id_for_label }}">
                            {{ form.first_name.label }}
                        </label>
                        {{ form.first_name }}
                        {% if form.first_name.errors %}
                            {% for error in form.first_name.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="w-full md:w-1/2 px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.last_name.id_for_label }}">
                            {{ form.last_name.label }}
                        </label>
                        {{ form.last_name }}
                        {% if form.last_name.errors %}
                            {% for error in form.last_name.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.email.id_for_label }}">
                            {{ form.email.label }}
                        </label>
                        {{ form.email }}
                        {% if form.email.errors %}
                            {% for error in form.email.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.birth_date.id_for_label }}">
                            {{ form.birth_date.label }}
                        </label>
                        {{ form.birth_date }}
                        {% if form.birth_date.errors %}
                            {% for error in form.birth_date.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.password1.id_for_label }}">
                            {{ form.password1.label }}
                        </label>
                        {{ form.password1 }}
                        {% if form.password1.errors %}
                            {% for error in form.password1.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.password2.id_for_label }}">
                            {{ form.password2.label }}
                        </label>
                        {{ form.password2 }}
                        {% if form.password2.errors %}
                            {% for error in form.password2.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.street_address.id_for_label }}">
                            {{ form.street_address.label }}
                        </label>
                        {{ form.street_address }}
                        {% if form.street_address.errors %}
                            {% for error in form.street_address.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="w-full md:w-1/2 px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.city.id_for_label }}">
                            {{ form.city.label }}
                        </label>
                        {{ form.city }}
                        {% if form.city.errors %}
                            {% for error in form.city.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.postal_code.id_for_label }}">
                            {{ form.postal_code.label }}
                        </label>
                        {{ form.postal_code }}
                        {% if form.postal_code.errors %}
                            {% for error in form.postal_code.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="w-full md:w-1/2 px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ form.country.id_for_label }}">
                            {{ form.country.label }}
                        </label>
                        {{ form.country }}
                        {% if form.country.errors %}
                            {% for error in form.country.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="flex items-center justify-between">
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                        Update
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/user_login.html
{% extends 'base.html' %}  {% block content %} {% if form.non_field_errors %} {% for error in form.non_field_errors %}
<div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
    <p class="font-bold">Error!</p>
    <p class="block sm:inline">{{ error }}</p>
</div>
{% endfor %} {% endif %}
<div class="grid grid-cols-3 gap-4">
    <div></div>
    <div class="py-2 px-3 rounded-xl bg-white mt-12">
        <h1 class="font-bold text-3xl text-center pb-5 shadow-md">Login</h1>
        <div class="w-full mt-10">
            <form method="post" class="shadow-md border border-gray-200 rounded px-8 pt-6 pb-8 mb-4">
                {% csrf_token %} {% for hidden_field in form.hidden_fields %} {{ hidden_field.errors }} {{ hidden_field }} {% endfor %} 
                {% for field in form.visible_fields %}
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
                {{ field.label }}
            </label>
                    <input class="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
                </div>
                {% if field.errors %} {% for error in field.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                {% endfor %} {% endif %} {% endfor %}

                <div class="flex items-center justify-center w-full">
                    <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Log In
            </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/user_registration.html
{% extends "base.html" %}
{% block content %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
            <p class="font-bold">Error!</p>
            <p class="block sm:inline">{{ error }}</p>
        </div>
    {% endfor %}
{% endif %}

<div class="bg-white px-3 py-4 rounded-xl my-6">
    <h1 class="font-bold text-3xl text-center pb-5">Sign In</h1>
    <div class="w-full mt-10">
        <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}

            {% for field in form.visible_fields %}
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ field.id_for_label }}">
                            {{ field.label }}
                        </label>
                        {{ field }}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Register
                </button>
            </div>
        </form>
    </div>
</div>

{% endblock %}